services:
    order-service:
        build:
          context: ./
          dockerfile: ./build/package/Dockerfile
        ports:
          - "8080:8080"
          - "9090:9090"
        depends_on:
          db:
            condition: service_healthy
        environment:
          - DB_HOST=db
          - DB_PORT=5432
          - DB_USER=postgres
          - DB_PASSWORD=postgres
          - DB_NAME=orders
        networks:
          - app-network

    db:
        image: postgres:17-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=orders
        ports:
          - "5432:5432"
        networks:
          - app-network
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
          interval: 5s
          timeout: 5s
          retries: 5

    admin:
      build:
        context: ./myadmin
        dockerfile: ./Dockerfile
      ports:
        - "9000:9000"
      depends_on:
        - order-service
      networks:
        - app-network

networks:
    app-network:
        driver: bridge